version: "2"

services:

     portainer:
         image: portainer/portainer
         command: ${PORTAINER_COMMAND}
         # -H unix:///var/run/docker.sock
         volumes:
             - '/var/run/docker.sock:/var/run/docker.sock'
             - '/tmp/portainer_password:/tmp/portainer_password'
         labels:
             - traefik.backend=portainer
             - traefik.port=9000
             - 'traefik.frontend.rule=Host:portainer.${DOMAIN}'
